swagger: '2.0'
info:
  version: '1.0.0'
  title: Notification Service
  description: Api Documentation for Notification service
basePath: /api/notification/v2
securityDefinitions:
  JWT:
    type: apiKey
    name: Authorization
    in: header
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /push-handlers/records-changed:
    post:
      description: recordChanged
      summary: recordChangedUsingPOST
      tags:
      - pubsub-endpoint
      operationId: recordChangedUsingPOST
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: data-partition-id
        in: header
        required: true
        type: string
        description: tenant
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
          headers: {}
        '201':
          description: Created
          headers: {}
        '401':
          description: Unauthorized
          headers: {}
        '403':
          description: Forbidden
          headers: {}
        '404':
          description: Not Found
          headers: {}
      security:
      - JWT: []
  /info:
    get:
      description: For deployment available public `/info` endpoint,  which provides build and git related information.
      summary: Version info
      tags:
      - info
      operationId: Versioninfo
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/VersionInfo'
          headers: {}
definitions:
  ResponseEntity:
    title: ResponseEntity
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
      statusCodeValue:
        type: integer
        format: int32
  VersionInfo:
    title: VersionInfo
    description: Version info.
    type: object
    properties:
      groupId:
        description: Maven artifact group ID.
        type: string
      actifactId:
        description: Maven artifact ID.
        type: string
      version:
        description: Maven artifact version
        type: string
      buildTime:
        description: Maven artifact build time
        type: string
      branch:
        description: Current git branch
        type: string
      commitId:
        description: Latest commit hash
        type: string
      commitMessage:
        description: Latest commit message
        type: string
      connectedOuterServices:
        description: Connected outer services information
        type: array
        items:
          $ref: '#/definitions/ConnectedOuterService'
  ConnectedOuterService:
    title: ConnectedOuterService
    description: Connected outer service information.
    type: object
    properties:
      name:
        description: Connected outer service name.
        type: string
      version:
        description: Connected outer service version.
        type: string
security: []
tags:
- name: pubsub-endpoint
  description: Pubsub Endpoint
- name: info
  description: Version info endpoint
