openapi: 3.0.1
info:
  title: Legal Service
  version: '1.0'
servers:
- url: /api/legal/v1
security:
- Authorization: []
paths:
  /legaltags:
    get:
      tags:
      - legal-tag-api
      operationId: listLegalTags
      parameters:
      - name: valid
        in: query
        required: false
        schema:
          type: boolean
          default: true
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LegalTagDtos'
    put:
      tags:
      - legal-tag-api
      operationId: updateLegalTag
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLegalTag'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LegalTagDto'
    post:
      tags:
      - legal-tag-api
      operationId: createLegalTag
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegalTagDto'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LegalTagDto'
  /legaltags:validate:
    post:
      tags:
      - legal-tag-api
      operationId: validateLegalTags
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestLegalTags'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/InvalidTagsWithReason'
  /legaltags:batchRetrieve:
    post:
      tags:
      - legal-tag-api
      operationId: getLegalTags
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestLegalTags'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LegalTagDtos'
  /legaltags:properties:
    get:
      tags:
      - legal-tag-api
      operationId: getLegalTagProperties
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ReadablePropertyValues'
  /legaltags/{name}:
    get:
      tags:
      - legal-tag-api
      operationId: getLegalTag
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    delete:
      tags:
      - legal-tag-api
      operationId: deleteLegalTag
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
                enum:
                - 100 CONTINUE
                - 101 SWITCHING_PROTOCOLS
                - 102 PROCESSING
                - 103 CHECKPOINT
                - 200 OK
                - 201 CREATED
                - 202 ACCEPTED
                - 203 NON_AUTHORITATIVE_INFORMATION
                - 204 NO_CONTENT
                - 205 RESET_CONTENT
                - 206 PARTIAL_CONTENT
                - 207 MULTI_STATUS
                - 208 ALREADY_REPORTED
                - 226 IM_USED
                - 300 MULTIPLE_CHOICES
                - 301 MOVED_PERMANENTLY
                - 302 FOUND
                - 302 MOVED_TEMPORARILY
                - 303 SEE_OTHER
                - 304 NOT_MODIFIED
                - 305 USE_PROXY
                - 307 TEMPORARY_REDIRECT
                - 308 PERMANENT_REDIRECT
                - 400 BAD_REQUEST
                - 401 UNAUTHORIZED
                - 402 PAYMENT_REQUIRED
                - 403 FORBIDDEN
                - 404 NOT_FOUND
                - 405 METHOD_NOT_ALLOWED
                - 406 NOT_ACCEPTABLE
                - 407 PROXY_AUTHENTICATION_REQUIRED
                - 408 REQUEST_TIMEOUT
                - 409 CONFLICT
                - 410 GONE
                - 411 LENGTH_REQUIRED
                - 412 PRECONDITION_FAILED
                - 413 PAYLOAD_TOO_LARGE
                - 413 REQUEST_ENTITY_TOO_LARGE
                - 414 URI_TOO_LONG
                - 414 REQUEST_URI_TOO_LONG
                - 415 UNSUPPORTED_MEDIA_TYPE
                - 416 REQUESTED_RANGE_NOT_SATISFIABLE
                - 417 EXPECTATION_FAILED
                - 418 I_AM_A_TEAPOT
                - 419 INSUFFICIENT_SPACE_ON_RESOURCE
                - 420 METHOD_FAILURE
                - 421 DESTINATION_LOCKED
                - 422 UNPROCESSABLE_ENTITY
                - 423 LOCKED
                - 424 FAILED_DEPENDENCY
                - 425 TOO_EARLY
                - 426 UPGRADE_REQUIRED
                - 428 PRECONDITION_REQUIRED
                - 429 TOO_MANY_REQUESTS
                - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
                - 451 UNAVAILABLE_FOR_LEGAL_REASONS
                - 500 INTERNAL_SERVER_ERROR
                - 501 NOT_IMPLEMENTED
                - 502 BAD_GATEWAY
                - 503 SERVICE_UNAVAILABLE
                - 504 GATEWAY_TIMEOUT
                - 505 HTTP_VERSION_NOT_SUPPORTED
                - 506 VARIANT_ALSO_NEGOTIATES
                - 507 INSUFFICIENT_STORAGE
                - 508 LOOP_DETECTED
                - 509 BANDWIDTH_LIMIT_EXCEEDED
                - 510 NOT_EXTENDED
                - 511 NETWORK_AUTHENTICATION_REQUIRED
  /jobs/updateLegalTagStatus:
    get:
      tags:
      - legal-tag-status-job-api
      operationId: checkLegalTagStatusChanges
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
                enum:
                - 100 CONTINUE
                - 101 SWITCHING_PROTOCOLS
                - 102 PROCESSING
                - 103 CHECKPOINT
                - 200 OK
                - 201 CREATED
                - 202 ACCEPTED
                - 203 NON_AUTHORITATIVE_INFORMATION
                - 204 NO_CONTENT
                - 205 RESET_CONTENT
                - 206 PARTIAL_CONTENT
                - 207 MULTI_STATUS
                - 208 ALREADY_REPORTED
                - 226 IM_USED
                - 300 MULTIPLE_CHOICES
                - 301 MOVED_PERMANENTLY
                - 302 FOUND
                - 302 MOVED_TEMPORARILY
                - 303 SEE_OTHER
                - 304 NOT_MODIFIED
                - 305 USE_PROXY
                - 307 TEMPORARY_REDIRECT
                - 308 PERMANENT_REDIRECT
                - 400 BAD_REQUEST
                - 401 UNAUTHORIZED
                - 402 PAYMENT_REQUIRED
                - 403 FORBIDDEN
                - 404 NOT_FOUND
                - 405 METHOD_NOT_ALLOWED
                - 406 NOT_ACCEPTABLE
                - 407 PROXY_AUTHENTICATION_REQUIRED
                - 408 REQUEST_TIMEOUT
                - 409 CONFLICT
                - 410 GONE
                - 411 LENGTH_REQUIRED
                - 412 PRECONDITION_FAILED
                - 413 PAYLOAD_TOO_LARGE
                - 413 REQUEST_ENTITY_TOO_LARGE
                - 414 URI_TOO_LONG
                - 414 REQUEST_URI_TOO_LONG
                - 415 UNSUPPORTED_MEDIA_TYPE
                - 416 REQUESTED_RANGE_NOT_SATISFIABLE
                - 417 EXPECTATION_FAILED
                - 418 I_AM_A_TEAPOT
                - 419 INSUFFICIENT_SPACE_ON_RESOURCE
                - 420 METHOD_FAILURE
                - 421 DESTINATION_LOCKED
                - 422 UNPROCESSABLE_ENTITY
                - 423 LOCKED
                - 424 FAILED_DEPENDENCY
                - 425 TOO_EARLY
                - 426 UPGRADE_REQUIRED
                - 428 PRECONDITION_REQUIRED
                - 429 TOO_MANY_REQUESTS
                - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
                - 451 UNAVAILABLE_FOR_LEGAL_REASONS
                - 500 INTERNAL_SERVER_ERROR
                - 501 NOT_IMPLEMENTED
                - 502 BAD_GATEWAY
                - 503 SERVICE_UNAVAILABLE
                - 504 GATEWAY_TIMEOUT
                - 505 HTTP_VERSION_NOT_SUPPORTED
                - 506 VARIANT_ALSO_NEGOTIATES
                - 507 INSUFFICIENT_STORAGE
                - 508 LOOP_DETECTED
                - 509 BANDWIDTH_LIMIT_EXCEEDED
                - 510 NOT_EXTENDED
                - 511 NETWORK_AUTHENTICATION_REQUIRED
  /info:
    get:
      tags:
      - info-api
      operationId: info
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
  /_ah/readiness_check:
    get:
      tags:
      - health-check-api
      operationId: readinessCheck
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /_ah/liveness_check:
    get:
      tags:
      - health-check-api
      operationId: livenessCheck
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /whoami:
    get:
      tags:
      - whoami-controller
      operationId: whoami
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    put:
      tags:
      - whoami-controller
      operationId: whoami_3
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
      - whoami-controller
      operationId: whoami_2
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    delete:
      tags:
      - whoami-controller
      operationId: whoami_5
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    options:
      tags:
      - whoami-controller
      operationId: whoami_6
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    head:
      tags:
      - whoami-controller
      operationId: whoami_1
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    patch:
      tags:
      - whoami-controller
      operationId: whoami_4
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /error:
    get:
      tags:
      - global-error-handler
      operationId: handleError
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
    put:
      tags:
      - global-error-handler
      operationId: handleError_3
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
    post:
      tags:
      - global-error-handler
      operationId: handleError_2
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
    delete:
      tags:
      - global-error-handler
      operationId: handleError_5
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
    options:
      tags:
      - global-error-handler
      operationId: handleError_6
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
    head:
      tags:
      - global-error-handler
      operationId: handleError_1
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
    patch:
      tags:
      - global-error-handler
      operationId: handleError_4
      parameters:
      - name: data-partition-id
        in: header
        description: Tenant Id
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    UpdateLegalTag:
      type: object
      properties:
        name:
          type: string
        contractId:
          type: string
        description:
          type: string
        expirationDate:
          type: string
          format: date-time
        extensionProperties:
          type: object
          additionalProperties:
            type: object
    LegalTagDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        properties:
          $ref: '#/components/schemas/Properties'
    Properties:
      type: object
      properties:
        countryOfOrigin:
          type: array
          items:
            type: string
        contractId:
          type: string
        expirationDate:
          type: string
          format: date-time
        originator:
          type: string
        dataType:
          type: string
        securityClassification:
          type: string
        personalData:
          type: string
        exportClassification:
          type: string
        extensionProperties:
          type: object
          additionalProperties:
            type: object
    RequestLegalTags:
      required:
      - names
      type: object
      properties:
        names:
          maxItems: 25
          minItems: 1
          type: array
          items:
            type: string
    InvalidTagWithReason:
      type: object
      properties:
        name:
          type: string
        reason:
          type: string
    InvalidTagsWithReason:
      type: object
      properties:
        invalidLegalTags:
          type: array
          items:
            $ref: '#/components/schemas/InvalidTagWithReason'
    LegalTagDtos:
      type: object
      properties:
        legalTags:
          type: array
          items:
            $ref: '#/components/schemas/LegalTagDto'
    ReadablePropertyValues:
      type: object
      properties:
        countriesOfOrigin:
          type: object
          additionalProperties:
            type: string
        otherRelevantDataCountries:
          type: object
          additionalProperties:
            type: string
        securityClassifications:
          uniqueItems: true
          type: array
          items:
            type: string
        exportClassificationControlNumbers:
          uniqueItems: true
          type: array
          items:
            type: string
        personalDataTypes:
          uniqueItems: true
          type: array
          items:
            type: string
        dataTypes:
          uniqueItems: true
          type: array
          items:
            type: string
    ConnectedOuterService:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
    VersionInfo:
      type: object
      properties:
        groupId:
          type: string
        artifactId:
          type: string
        version:
          type: string
        buildTime:
          type: string
        branch:
          type: string
        commitId:
          type: string
        commitMessage:
          type: string
        connectedOuterServices:
          type: array
          items:
            $ref: '#/components/schemas/ConnectedOuterService'
  securitySchemes:
    Authorization:
      type: http
      scheme: Bearer
      bearerFormat: Authorization
